version: '3'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    # 使用宿主机网络
    # network_mode: "host"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/usr/share/nginx/html
      - ./www:/var/www
      - ./logs:/var/log/nginx
      # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
      - ./nginx.conf/:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true